version: "3.8"
services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
